CREATE TABLE IF NOT EXISTS user(
	id BLOB PRIMARY KEY NOT NULL,
	name TEXT NOT NULL
);


CREATE TABLE IF NOT EXISTS goal(
	id BLOB PRIMARY KEY NOT NULL,
	title TEXT NOT NULL,
	user_id BLOB NOT NULL,
	FOREIGN KEY(user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS goal_entry(
	date TEXT NOT NULL,
	goal_id BLOB NOT NULL,
	PRIMARY KEY (date, goal_id)
	FOREIGN KEY(goal_id) REFERENCES goal(id) ON DELETE CASCADE ON UPDATE CASCADE
);

